### ISSUE TITLE
Shape Mismatch

### ISSUE THREAD

**Issue by albertnanda** [xuxingya/tf2crf#1]
Hi, 
I am trying to train a NER model, 
I am trying out your code:
from tensorflow.keras.layers import Input, Embedding, Bidirectional, GRU, Dense
from tensorflow.keras.models import Model
crf = CRF()

inputs = Input(shape=(None,), dtype='int32')
output = Embedding(100, 40, trainable=True, mask_zero=True)(inputs)
output = Bidirectional(GRU(64, return_sequences=True))(output)
output = Dense(9, activation=None)(output)
output = crf(output)
model = Model(inputs, output)
model.compile(loss=crf.loss, optimizer='adam', metrics=[crf.accuracy])

x = [[5,2,3]*3]*10
y=[[1,2,3]*3]*10

model.fit(x=x,y=y,epochs=2,batch_size=2)

But this bugs out. Do i need to one-hot encode my labels?

**Comment by xuxingya** [comment]
no ,yo don't need to one-hot encode. `output= Dense(9, activation=None)(output)` , so your have 9 labels? Make sure the unit num equals to your label num.

**Comment by albertnanda** [comment]
Yes, 9 labels ..here is my test data:
y = np.array([list(range(9))]*10)
x = np.array([list(range(1,10))]*10)
x.shape -->(10,9)
y.shape -- > (10,9)

Error:
ValueError: Dimensions must be equal, but are 10 and 9 for '{{node add_1}} = AddV2[T=DT_INT32](add, add_1/loss/Cast)' with input shapes: [2,10], [2,9].
Though, I am running this code on tf 2.2.0? do you think that's causing the error?

**Comment by xuxingya** [comment]
I tried the same code on tf 2.2.0, but it works. This is my code:
![image](https://user-images.githubusercontent.com/13343428/82652183-c209e800-9c4f-11ea-8bce-b3dcb9f87d31.png)
I think the problem is not the code above.
Plz check the version of tensorflow-addons, my version is 0.8.3. I think any higher version also works.

**Comment by albertnanda** [comment]
Not sure what the problem could be, reinstalled everything, still the same bug. I have attached my notebook for your reference.
[crf_error.zip](https://github.com/xuxingya/tf2crf/files/4667946/crf_error.zip)

**Comment by prince14322** [comment]
`      y_pred = K.cast(viterbi_sequence, y_true.dtype)
        y_pred = K.argmax(y_pred, -1)
        y_true = K.argmax(y_true, -1)  # -> i added this line, here there was a shape mismatch
        y_true = K.cast(y_true, y_pred.dtype)`
this worked for me.

**Comment by prince14322** [comment]
` y_pred = K.cast(viterbi_sequence, y_true.dtype)
y_pred = K.argmax(y_pred, -1)
y_true = K.argmax(y_true, -1) # -> i added this line, here there was a shape mismatch
y_true = K.cast(y_true, y_pred.dtype)`

this worked for me.

**Comment by xuxingya** [comment]
> Not sure what the problem could be, reinstalled everything, still the same bug. I have attached my notebook for your reference.
> [crf_error.zip](https://github.com/xuxingya/tf2crf/files/4667946/crf_error.zip)

U

> Not sure what the problem could be, reinstalled everything, still the same bug. I have attached my notebook for your reference.
> [crf_error.zip](https://github.com/xuxingya/tf2crf/files/4667946/crf_error.zip)

Thank you for your Notebook. These is a bug in accuracy function. I just fixed it and made an update.

**Comment by xuxingya** [comment]
> ` y_pred = K.cast(viterbi_sequence, y_true.dtype) y_pred = K.argmax(y_pred, -1) y_true = K.argmax(y_true, -1) # -> i added this line, here there was a shape mismatch y_true = K.cast(y_true, y_pred.dtype)`
> 
> this worked for me.
The second dim is time steps. Instead of add the new line, please delete 'y_pred = K.argmax(y_pred, -1)'. I have already fixed the bug in the accuracy function.

**Comment by Gorodecki** [comment]
When are you planning to update the version?

**Comment by Gorodecki** [comment]
> > ` y_pred = K.cast(viterbi_sequence, y_true.dtype) y_pred = K.argmax(y_pred, -1) y_true = K.argmax(y_true, -1) # -> i added this line, here there was a shape mismatch y_true = K.cast(y_true, y_pred.dtype)`
> > this worked for me.
> > The second dim is time steps. Instead of add the new line, please delete 'y_pred = K.argmax(y_pred, -1)'. I have already fixed the bug in the accuracy function.

When are you planning to update the version?

**Comment by xuxingya** [comment]
> > > ` y_pred = K.cast(viterbi_sequence, y_true.dtype) y_pred = K.argmax(y_pred, -1) y_true = K.argmax(y_true, -1) # -> i added this line, here there was a shape mismatch y_true = K.cast(y_true, y_pred.dtype)`
> > > this worked for me.
> > > The second dim is time steps. Instead of add the new line, please delete 'y_pred = K.argmax(y_pred, -1)'. I have already fixed the bug in the accuracy function.
> 
> When are you planning to update the version?

Already update
