### ISSUE TITLE
crf.accuracy always equals 0

### ISSUE THREAD

**Issue by wfge** [xuxingya/tf2crf#14]
when I set mask_zero=False in the embedding layer ,the accuracy will always be 0,like this
Epoch 1/100
28/28 [==============================] - 1s 46ms/step - loss: 90.9821 - accuracy: 0.0000e+00
Epoch 2/100
28/28 [==============================] - 1s 46ms/step - loss: 36.3541 - accuracy: 0.0000e+00
Epoch 3/100
28/28 [==============================] - 1s 46ms/step - loss: 31.0853 - accuracy: 0.0000e+00
Epoch 4/100
28/28 [==============================] - 1s 46ms/step - loss: 27.0876 - accuracy: 0.0000e+00
Epoch 5/100
19/28 [===================>..........] - ETA: 0s - loss: 24.5962 - accuracy: 0.0000e+00

**Comment by xuxingya** [comment]
I will test it on Monday. Thank you.

**Comment by xuxingya** [comment]
There is a bug in calculating accuracy when mask_zero=False. FIx it in new version.
