### ISSUE TITLE
val_accuracy 

### ISSUE THREAD

**Issue by wfge** [xuxingya/tf2crf#16]
Hi，When I use validation datasets in the model.fit_generator function,the val_accuracy is very low,and in addition，when i use the new edition of tf2crf，the val_acc has a big difference to the old edition of tf2crf
-----------------
**this is the result when i use the old edtion of  tf2crf ,with set mask=True**
![image](https://user-images.githubusercontent.com/16102198/96552058-d416b200-12e5-11eb-9e47-49385381d3cb.png)

**this is the result when i use the new edtion of tf2crf,with set mask=True,as you can see ,the val_acc is very low**
![image](https://user-images.githubusercontent.com/16102198/96554502-32915f80-12e9-11eb-85be-2045f6d62831.png)

**Comment by xuxingya** [comment]
Could you add the version number? Then I can test it.

**Comment by wfge** [comment]
---
I am sorry,it is my fault not to use the correct version。。。。
But I found a new bug in the tf2crf on the latest version 0.1.21  
when i set mask=False in the embedding layer,and use valid_data in model.fit_generator() function,like this
---

![image](https://user-images.githubusercontent.com/16102198/96721099-4074dc80-13de-11eb-94fe-6e15aff7eef7.png)
---
then traing the model,when  calculate the val_acc,there is a crash，like this
---
![image](https://user-images.githubusercontent.com/16102198/96721429-b2e5bc80-13de-11eb-85e1-30721f591850.png)
---
Then I modified the source code of the accuracy function in tf2crf，the code works！I changed here
---
![image](https://user-images.githubusercontent.com/16102198/96721899-58009500-13df-11eb-8d03-c12f9299bc2d.png)
---
do u think I've revised it correctly？THX！
---

**Comment by wfge** [comment]
I am sorry,it is my fault not to use the correct version。。。。
But I found a new bug in the tf2crf on the latest version 0.1.21

**Comment by xuxingya** [comment]
Yes, you are right.
I will solve this in next version.
Thank you!
