### ISSUE TITLE
Arguments/Methods in the CRF class are not well documented

### ISSUE THREAD

**Issue by eloukas** [xuxingya/tf2crf#20]
Some examples:

- `num_labels`: There is no variable called `num_labels`. Maybe you mean output_dim?
- `output_dim`: Why give it as an input if it's getting overwritten in the `build()` method, using the input_shape?
- I think you should also state that you **must expect** a linear Dense layer before the CRF, so you have a correct input_shape. Otherwise, the input_shapes are not correct.
- The 2 methods `compute_output_shape` and `compute_mask` are not used currently.

I'm telling this because it's harder for someone to debug their model at this moment.

Thank you for your time.

**Comment by xuxingya** [comment]
Thank you for your advices,
I have made it better at the new version..
