### ISSUE TITLE
ValueError: indices.shape[-1] must be <= params.rank

### ISSUE THREAD

**Issue by meysamgolm1360** [xuxingya/tf2crf#23]
I have a model that has just one output, but I get this error:

ValueError: indices.shape[-1] must be <= params.rank, but saw indices shape: [?,2] and params shape: [?] for '{{node cond/GatherNd}} = GatherNd[Tindices=DT_INT32, Tparams=DT_INT32](cond/GatherNd/Cast, cond/concat)' with input shapes: [?], [?,2].

Here is the model:

`    
    # build CNN/LSTM and train it.
    #
    input = Input(shape=(210, 20, 26, 1,))
    
    output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(input)
    output = Activation('elu')(output)
    output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
    output = Dropout(0.2)(output)
    
    output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
    output = Activation('elu')(output)
    output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
    output = Dropout(0.2)(output)
    
    output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
    output = Activation('elu')(output)
    output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
    output = Dropout(0.2)(output)
    
    output =  TimeDistributed(Flatten())(output)
    
    output =  Conv1D(16, 3, padding='same')(output)
    output =  Activation('elu')(output)
    output =  MaxPooling1D(pool_size=8)(output)
    
    output =  Bidirectional(LSTM(64, return_sequences=True))(output)
    output =  Activation('elu')(output)
    
    output =  TimeDistributed(Dense(1, activation='relu'))(output)
    
    crf=CRF(dtype='float32')
    output = crf(output)
    base_model = Model(input, output)
    model = ModelWithCRFLoss(base_model)
    model.compile(optimizer='adam')
    
    ## Training part..
    
    model.fit_generator(generator=train_data, \
                        epochs=int(lstm_p["epoch_size"]), \
                        verbose=1, \
                        callbacks=[checkpointer], \
                        use_multiprocessing=True, \
                        max_queue_size=10,\
                        workers=12)`
I appreciate if you look at this problem and let me know about the reasons.

**Comment by xuxingya** [comment]
Just put a Dense(units=tag_nums) before the CRF layer. The last dim of crf
input should be the numbers of tags you want to predict.

**Comment by meysamgolm1360** [comment]
Thank you for your reply. I changed the model based on your comment, but I still get the same error. Here is the new model:

`input = Input(shape=(210, 20, 26, 1,))

output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(input)
output = Activation('elu')(output)
output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
output = Dropout(0.2)(output)

output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
output = Activation('elu')(output)
output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
output = Dropout(0.2)(output)

output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
output = Activation('elu')(output)
output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
output = Dropout(0.2)(output)

output =  TimeDistributed(Flatten())(output)

output =  Conv1D(16, 3, padding='same')(output)
output =  Activation('elu')(output)
output =  MaxPooling1D(pool_size=8)(output)

output =  Bidirectional(LSTM(64, return_sequences=True))(output)
output =  Activation('elu')(output)

output =  TimeDistributed(Dense(1, activation='relu'))(output)

crf=CRF(dtype='float32')
output = crf(output)
base_model = Model(input, output)
model = ModelWithCRFLoss(base_model)
model.compile(optimizer='adam')

#Training part..

model.fit_generator(generator=train_data, \
                    epochs=int(lstm_p["epoch_size"]), \
                    verbose=1, \
                    callbacks=[checkpointer], \
                    use_multiprocessing=True, \
                    max_queue_size=10,\
                    workers=12)`

**Comment by xuxingya** [comment]
Replace the '1'  with the numbers of tags you want to predict in `output =
TimeDistributed(Dense(1, activation='relu'))(output)`.

You can try this example to help understand:

input = Input(shape=(210, 20, 26, 1))

output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(input)
output = Activation('elu')(output)
output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
output = Dropout(0.2)(output)

output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
output = Activation('elu')(output)
output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
output = Dropout(0.2)(output)

output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
output = Activation('elu')(output)
output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
output = Dropout(0.2)(output)

output = TimeDistributed(Flatten())(output)

output = Conv1D(16, 3, padding='same')(output)
output = Activation('elu')(output)
output = MaxPooling1D(pool_size=8)(output)

output = Bidirectional(LSTM(64, return_sequences=True))(output)
output = Activation('elu')(output)

output = TimeDistributed(Dense(26, activation='relu'))(output)
crf = CRF(dtype='float32')
output = crf(output)
base_model = Model(input, output)
model = ModelWithCRFLoss(base_model)
model.compile(optimizer='adam')
x = np.array([[[[5, 2] * 13] * 20]*210]*100)
y = np.array([list(range(26))] * 100)
model.fit(x=x, y=y, epochs=10,verbose=1, batch_size=4)

**Comment by meysamgolm1360** [comment]
But I have two tags in my project which means my project is bi-classification. In that case, I always write the dense layer like this:  TimeDistributed(Dense(1, activation='relu'))(output). Having two outputs is not necessary, since the signal can't have both tags at the same time. Does library support Dense(1) output?

**Comment by xuxingya** [comment]
The CRF layer means to calculate the transition probabilities between tags. So if you only have one tag, you don't need to use CRF.
If you really want to use CRF, set TimeDistributed(Dense(2, activation='relu'))(output), and use 0 and 1 as tags.
You can compare the performance to decide whether to use or not.

**Comment by meysamgolm1360** [comment]
Thank you for your reply. After our conversation, I made a lot of changes in my scripts based on your advice. I still get an error:

`ValueError: Shape must be rank 2 but is rank 3 for '{{node cond/Slice}} = Slice[Index=DT_INT32, T=DT_INT32](cond/add_1/Cast, cond/Slice/begin, cond/Slice/size)' with input shapes: [?,?,?], [2], [2].`

I assume this error is related to how tf2crf handles batch size. Let go into details; here is the length of my feature and my label:

feats.shape =  (32, 210, 20, 26, 1) 
labels.shape =  (32, 21, 2) 

In above vectors, 32 is batch size, I have 21 time steps and 2 tags. I saw in your toy examples, when you want pass feats and labels, you don't compose batch of data. But since I use fit_generator, I need to compose batch of data by myself. Does tf2crf library work with such inputs and fit_generator?

Finally here is the model:

```
    model = Sequential()

    input = Input(shape=(210, 20, 26, 1,))
    
    output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(input)
    output = Activation('elu')(output)
    output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
    output = Dropout(0.2)(output)
    
    output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
    output = Activation('elu')(output)
    output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
    output = Dropout(0.2)(output)
    
    output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
    output = Activation('elu')(output)
    output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
    output = Dropout(0.2)(output)
    
    output =  TimeDistributed(Flatten())(output)
    
    output =  Conv1D(16, 3, padding='same')(output)
    output =  Activation('elu')(output)
    output =  MaxPooling1D(pool_size=10)(output)

    output =  Bidirectional(LSTM(64, return_sequences=True))(output)
    output =  Activation('elu')(output)
    
    output = TimeDistributed(Dense(2, activation='relu'))(output)
    
    crf=CRF(dtype='float32')
    output = crf(output)
    base_model = Model(input, output)
    model = ModelWithCRFLoss(base_model)
    model.compile(optimizer='adam')

    model.fit_generator(generator=train_data, \
                        epochs=10), \
                        verbose=1, \
                        callbacks=[checkpointer], \
                        use_multiprocessing=True, \
                        max_queue_size=10,\
                        workers=12)
```
I use tf.keras.utils.Sequence to generate batch of data.

**Comment by xuxingya** [comment]
if you want to use generator, fit_generator is not recommended, instead you can use: model.fit(x=generator)
For a full example:
```
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model
from tensorflow.keras.utils import Sequence
import numpy as np
from tf2crf import CRF, ModelWithCRFLoss, ModelWithCRFLossDSCLoss

input = Input(shape=(210, 20, 26, 1))

output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(input)
output = Activation('elu')(output)
output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
output = Dropout(0.2)(output)

output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
output = Activation('elu')(output)
output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
output = Dropout(0.2)(output)

output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
output = Activation('elu')(output)
output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
output = Dropout(0.2)(output)

output = TimeDistributed(Flatten())(output)

output = Conv1D(16, 3, padding='same')(output)
output = Activation('elu')(output)
output = MaxPooling1D(pool_size=8)(output)

output = Bidirectional(LSTM(64, return_sequences=True))(output)
output = Activation('elu')(output)

output = TimeDistributed(Dense(2, activation='relu'))(output)
crf = CRF(dtype='float32')
output = crf(output)
base_model = Model(input, output)
model = ModelWithCRFLoss(base_model)
model.compile(optimizer='adam')
x = [[[[5, 2] * 13] * 20]*210]*100
y = [[0, 1]*13] * 100


class data_generator(Sequence):
    def __init__(self, data, batch_size=4, shuffle=False):
        self.data = data
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.indexes = np.arange(len(data))
        self.on_epoch_end()

    def __len__(self):
        return int(np.floor(len(self.data) / self.batch_size))

    def __getitem__(self, index):
        """Generate one batch of data"""
        # Generate indexes of the batch
        indexes = self.indexes[index * self.batch_size:(index + 1) * self.batch_size]
        # Generate data
        x_out, y_out = self.__data_generation(indexes)

        return x_out, y_out

    def on_epoch_end(self):
        """Updates indexes after each epoch"""
        if self.shuffle:
            np.random.shuffle(self.indexes)

    def __data_generation(self, idxs):
        X, Y = [], []
        for i in idxs:
            d = self.data[i]
            X.append(d[0])
            Y.append(d[1])
        return np.array(X), np.array(Y)

gen = data_generator(list(zip(x,y)), 4)
model.fit(x=gen, epochs=100, verbose=1)
```
My result:
```
Epoch 1/100
25/25 [==============================] - 7s 289ms/step - crf_loss: 8.3872 - accuracy: 0.0400
Epoch 2/100
25/25 [==============================] - 5s 218ms/step - crf_loss: 8.0507 - accuracy: 0.5200
Epoch 3/100
25/25 [==============================] - 5s 195ms/step - crf_loss: 7.7451 - accuracy: 1.0000
Epoch 4/100
25/25 [==============================] - 5s 185ms/step - crf_loss: 7.4557 - accuracy: 1.0000
Epoch 5/100
25/25 [==============================] - 5s 192ms/step - crf_loss: 7.1816 - accuracy: 1.0000
```

**Comment by meysamgolm1360** [comment]
Thank you for your reply. Your example made it clear for me and now my script is working fine. Thanks
