### ISSUE TITLE
error in building model

### ISSUE THREAD

**Issue by meysamgolm1360** [xuxingya/tf2crf#24]
Hi, I get an error when I want to build a CNN/LSTM/CRF. Here is the model:

    input_shape=(210, 20, 26, 1,)
    # build CNN/LSTM and train it.
    #
    input = Input(input_shape)
    
    output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(input)
    output = Activation('elu')(output)
    output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
    output = Dropout(0.2)(output)
    
    output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
    output = Activation('elu')(output)
    output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
    output = Dropout(0.2)(output)
    
    output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
    output = Activation('elu')(output)
    output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
    output = Dropout(0.2)(output)
    
    output =  TimeDistributed(Flatten())(output)
    
    output =  Conv1D(16, 3, padding='same')(output)
    output =  Activation('elu')(output)
    output =  MaxPooling1D(pool_size=10)(output)
    output =  Bidirectional(LSTM(64, return_sequences=True))(output)
    output =  Activation('elu')(output)
    
    output = TimeDistributed(Dense(2, activation='relu'))(output)
    
    crf=CRF(dtype='float32')
    output = crf(output)
    base_model = Model(input, output)
    model = ModelWithCRFLoss(base_model)
    model.compile(optimizer='adam')
    model.build(input_shape)
    model.summary()

Here is the error:

`ValueError: Input 0 is incompatible with layer time_distributed: expected shape=[None, None, 20, 26, 1], found shape=[210, 20, 26, 1, 1]`

Note that I can build the same model when I remove CRF from the model. Here is the model that I can build
  
    input_shape=(210, 20, 26, 1,)
    # build CNN/LSTM and train it.
    #
    input = Input(input_shape)
    
    output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(input)
    output = Activation('elu')(output)
    output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
    output = Dropout(0.2)(output)
    
    output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
    output = Activation('elu')(output)
    output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
    output = Dropout(0.2)(output)
    
    output = TimeDistributed(Conv2D(16, (3, 3), padding='same'))(output)
    output = Activation('elu')(output)
    output = TimeDistributed(MaxPooling2D(pool_size=(2, 2)))(output)
    output = Dropout(0.2)(output)
    
    output =  TimeDistributed(Flatten())(output)
    
    output =  Conv1D(16, 3, padding='same')(output)
    output =  Activation('elu')(output)
    output =  MaxPooling1D(pool_size=10)(output)
    output = Bidirectional(LSTM(64, return_sequences=False))(output)
    output = Activation('elu')(output)
    output = Dense(1, activation='sigmoid')(output)
    
    model = Model(input, output)
    
    adam_mgm = keras.optimizers.Adam(lr=0.0005, beta_1=0.9, beta_2=0.999, \
                                     epsilon=1e-08, decay=0.0001)
    model.compile(loss='mean_squared_error', optimizer=adam_mgm, \
                  metrics=['accuracy'])

**Comment by xuxingya** [comment]
Change to `model.build((None, 210, 20, 26, 1))`. Here you need to add the batch dim, which is None.

**Comment by meysamgolm1360** [comment]
Worked for me! Thanks
