### ISSUE TITLE
dsc_loss goes nan

### ISSUE THREAD

**Issue by musiclord** [xuxingya/tf2crf#26]
In some cases during training, dsc_loss or crf_loss may become nan value, also the output of prediction...
```Epoch 00005: val_dsc_loss_val improved from 0.30640 to 0.30055, saving model to TrainedModels\2BiLSTM-dsc_test.h5
234/234 [==============================] - 510s 2s/step - crf_loss: 0.3793 - dsc_loss: 0.3030 - accuracy: 0.9866 - val_crf_loss_val: 1.8332 - val_dsc_loss_val: 0.3005 - val_val_accuracy: 0.9850
Epoch 6/30
234/234 [==============================] - ETA: 0s - crf_loss: nan - dsc_loss: nan - accuracy: 0.9804        
Epoch 00006: val_dsc_loss_val did not improve from 0.30055
234/234 [==============================] - 510s 2s/step - crf_loss: nan - dsc_loss: nan - accuracy: 0.9804 - val_crf_loss_val: nan - val_dsc_loss_val: nan - val_val_accuracy: 0.0000e+00
C:\Users\rich2\miniconda3\envs\tf\lib\site-packages\tensorflow\python\keras\callbacks.py:1291: RuntimeWarning: invalid value encountered in less
  if self.monitor_op(current, self.best):
C:\Users\rich2\miniconda3\envs\tf\lib\site-packages\tensorflow\python\keras\callbacks.py:1664: RuntimeWarning: invalid value encountered in less
  if self.monitor_op(current - self.min_delta, self.best):
Epoch 7/30
234/234 [==============================] - ETA: 0s - crf_loss: nan - dsc_loss: nan - accuracy: 0.0000e+00  
Epoch 00007: val_dsc_loss_val did not improve from 0.30055
234/234 [==============================] - 509s 2s/step - crf_loss: nan - dsc_loss: nan - accuracy: 0.0000e+00 - val_crf_loss_val: nan - val_dsc_loss_val: nan - val_val_accuracy: 0.0000e+00

**Comment by Pol-Zeimet** [comment]
```
Epoch 1/5
100/100 [==============================] - ETA: 0s - crf_loss: 419.2427 - accuracy: 0.9564 - val_crf_loss_val: 347.5040 - val_val_accuracy: 0.9576
Epoch 2/5
100/100 [==============================] - 305s 3s/step - crf_loss: -3201.3066 - accuracy: 0.9569 - val_crf_loss_val: 287.6088 - val_val_accuracy: 0.9575
Epoch 3/5
100/100 [==============================] - ETA: 0s - crf_loss: -1635656.3878 - accuracy: 0.9569
```

I have quite a similar issue. My loss has a high negative value....

**Comment by xuxingya** [comment]
> ```
> Epoch 1/5
> 100/100 [==============================] - ETA: 0s - crf_loss: 419.2427 - accuracy: 0.9564 - val_crf_loss_val: 347.5040 - val_val_accuracy: 0.9576
> Epoch 2/5
> 100/100 [==============================] - 305s 3s/step - crf_loss: -3201.3066 - accuracy: 0.9569 - val_crf_loss_val: 287.6088 - val_val_accuracy: 0.9575
> Epoch 3/5
> 100/100 [==============================] - ETA: 0s - crf_loss: -1635656.3878 - accuracy: 0.9569
> ```
> 
> I have quite a similar issue. My loss has a high negative value....

Negative loss is usually caused by masking. Do you use padding and masking in your model?

**Comment by xuxingya** [comment]
> In some cases during training, dsc_loss or crf_loss may become nan value, also the output of prediction...
> 
> ```
> 234/234 [==============================] - 510s 2s/step - crf_loss: 0.3793 - dsc_loss: 0.3030 - accuracy: 0.9866 - val_crf_loss_val: 1.8332 - val_dsc_loss_val: 0.3005 - val_val_accuracy: 0.9850
> Epoch 6/30
> 234/234 [==============================] - ETA: 0s - crf_loss: nan - dsc_loss: nan - accuracy: 0.9804        
> Epoch 00006: val_dsc_loss_val did not improve from 0.30055
> 234/234 [==============================] - 510s 2s/step - crf_loss: nan - dsc_loss: nan - accuracy: 0.9804 - val_crf_loss_val: nan - val_dsc_loss_val: nan - val_val_accuracy: 0.0000e+00
> C:\Users\rich2\miniconda3\envs\tf\lib\site-packages\tensorflow\python\keras\callbacks.py:1291: RuntimeWarning: invalid value encountered in less
>   if self.monitor_op(current, self.best):
> C:\Users\rich2\miniconda3\envs\tf\lib\site-packages\tensorflow\python\keras\callbacks.py:1664: RuntimeWarning: invalid value encountered in less
>   if self.monitor_op(current - self.min_delta, self.best):
> Epoch 7/30
> 234/234 [==============================] - ETA: 0s - crf_loss: nan - dsc_loss: nan - accuracy: 0.0000e+00  
> Epoch 00007: val_dsc_loss_val did not improve from 0.30055
> 234/234 [==============================] - 509s 2s/step - crf_loss: nan - dsc_loss: nan - accuracy: 0.0000e+00 - val_crf_loss_val: nan - val_dsc_loss_val: nan - val_val_accuracy: 0.0000e+00
> ```

I am not sure this is the problem of CRF. The training data and model may cause nan loss. You can try softmax and check if it works.

**Comment by Pol-Zeimet** [comment]
> Negative loss is usually caused by masking. Do you use padding and masking in your model?

Yes I do. Seems like I have to use a different approach. By any chance, do you have any recommendation concerning padding/masking for the  crf layer? 
I am currently also experimenting with tf.keras.layers.Masking() And it seems like it causes an error in batch_crf_loss:
(see (0) InvalidArgument )
```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [weights can not be broadcast to values.] [weights.shape=] [Cast_3:0] [5 173] [values.shape=] [Cast_2:0] [5 512] [is_scalar=] [0]
	 [[{{node broadcast_weights/assert_broadcastable/AssertGuard/else/_1187/broadcast_weights/assert_broadcastable/AssertGuard/Assert}}]]
	 [[cond_2/then/_1197/batch_crf_loss/ReadVariableOp/_368]]
  (1) Invalid argument:  assertion failed: [weights can not be broadcast to values.] [weights.shape=] [Cast_3:0] [5 173] [values.shape=] [Cast_2:0] [5 512] [is_scalar=] [0]
	 [[{{node broadcast_weights/assert_broadcastable/AssertGuard/else/_1187/broadcast_weights/assert_broadcastable/AssertGuard/Assert}}]]```

**Comment by xuxingya** [comment]
You can try to calculate the mask from your inputs and give it directly to
the CRF layer by CRF(mask=calculated_mask). I think this will help find the
problem. You can also check the shape of the mask by
Layer.compute_mask(input).

**Comment by Pol-Zeimet** [comment]
Okay, I figured it out.
I tried out a few ways to do my masking, but the error kept coming up. 
I finally got it to work when placing a second masking layer right in front of the crf layer.
Here is a snipped of my code:
``` 
 #Defining Layers
  #...
  #[...]some embedding layers[...]
  #...

  masking = Masking(name = 'masking')
  bilstm = Bidirectional(LSTM(64, return_sequences=True), name = 'bilstm', )
  activation =  TimeDistributed(Activation('relu'), name = 'relu_activation')
  pre_crf_layer_1 = TimeDistributed(Dense(64, activation='relu'), name = 'pre_crf_layer_1')
  pre_crf_layer_2 = TimeDistributed(Dense(num_classes, activation='softmax'), name = 'pre_crf_layer_2')
  crf_layer = CRF(name = 'crf_layer' )

 #defining Model
 #...
 #[...]some embedding layers[...]
 #...

  x = masking(x)
  mask_1 = masking.compute_mask(x)
  x = bilstm(x, mask = mask_1)
  x = activation(x)
  x = pre_crf_layer_1(x)
  x = pre_crf_layer_2(x)
  x = masking(x)
  mask_2 = masking.compute_mask(x)
  output = crf_layer(x, mask = mask_2)
  
  masked_sequence = masking(latent_activatet_sequence)
  mask = masking.compute_mask(masked_sequence)
  output = crf_layer(masked_sequence, mask = mask)
```

I was surprised, as I thought the mask would be passed trough by the BiLSTM Layer.
Anyways, I hope this may help someone with similar issues.

Regards,
Pol

**Comment by danielbulhosa** [comment]
@musiclord did you ever solve the issue with the nan crf_loss? I'm getting the same issue. @xuxingya where would I put the softmax to see if I can fix the issue, in the dense layer before the CRF layer?

**Comment by xuxingya** [comment]
Please upgrade to the new version, now you can implement the crf layer like
this: CRF(units=[num of categories]).
Nan loss can be caused by many reasons. You can check these methods below:
1. make sure your mask layer is correct
2. check using sparse data or not (check 'sparse_target' parameter of the
ModelWapper)
3. add a LayerNormalization before the CRF layer to make it stable.
4. smaller learning rate
...

**Comment by danielbulhosa** [comment]
Thanks for the tips! I think the error was in my end. I did custom padding and was using np.empty instead of np.zeros to create the padded time steps. I learned a lot about the features of the module from digging into suggestions though.
