### ISSUE TITLE
Error by importing tf2crf

### ISSUE THREAD

**Issue by afi1289** [xuxingya/tf2crf#30]
Hello, 
I think there is a simple error in your explanation because I couldn't import ```tf2CRF``` with capital letters for ```CRF```
```
import tensorflow as tf
from tf2CRF import CRF 
from tensorflow.keras.layers import Input, Embedding, Bidirectional, GRU, Dense
from tensorflow.keras.models import Model
from tf2crf import CRF, ModelWithCRFLoss
```
Thank you!

**Comment by xuxingya** [comment]
You are right. There is an error in the Readme.
Thank you very much!
