### ISSUE TITLE
Issue: 'Keyword argument not understood:', 'units'

### ISSUE THREAD

**Issue by zlindaz2411** [xuxingya/tf2crf#34]
I copied and pasted the code from ReadME and it gives me the following error. I have the latest version of tensorflow and tensorflow_addons.

<img width="1022" alt="Screenshot 2021-03-17 at 20 48 52" src="https://user-images.githubusercontent.com/32620429/111536481-332c0600-8762-11eb-9f18-a1d4847e2ccc.png">

**Comment by xuxingya** [comment]
I am sorry I forget to upload the new code to pip. You can update the
package now and it will be fixed.

**Comment by zlindaz2411** [comment]
Thank you. The example now works. 
I have another problem. I'm currently implementing a model for the span identification task. I am using BERT model and then CRF layers. Each output consists of a tuple of one-hot vector: one representing the start index and the other representing the end index of the span. 

Here is the implementation:
<img width="555" alt="Screenshot 2021-03-18 at 12 53 00" src="https://user-images.githubusercontent.com/32620429/111629611-636ab780-87e9-11eb-95e9-8d9c2364ce75.png">

However, I"m getting the following error is sparse_target is set to True 
<img width="841" alt="Screenshot 2021-03-18 at 12 57 18" src="https://user-images.githubusercontent.com/32620429/111629698-7b423b80-87e9-11eb-9bf7-09efdbece0b0.png">

and this error if sparse_target is set to False
<img width="824" alt="Screenshot 2021-03-18 at 12 58 46" src="https://user-images.githubusercontent.com/32620429/111629902-b04e8e00-87e9-11eb-9ae8-ace2c5fb51f0.png">

**Comment by xuxingya** [comment]
According to your model, I think you have to custom the ModelWapper
yourself. Because it doesn't support two CRF at the same time. Please refer
to the source code in my github.
