### ISSUE TITLE
Unable to save model

### ISSUE THREAD

**Issue by Arsyad-ah** [xuxingya/tf2crf#4]
Hi, I'm not able to save the CRF model out after training. Seems that output_dim is not an attribute of the class. Any advise on this?

> ~/.local/lib/python3.6/site-packages/tf2crf/crf.py in get_config(self)
     35     def get_config(self):
     36         config = {
---> 37             "output_dim": self.output_dim,
     38             "transitions": K.eval(self.transitions),
     39         }
AttributeError: 'CRF' object has no attribute 'output_dim'

**Comment by xuxingya** [comment]
I will fix this tomorrow. -------- 原始邮件 --------发件人： Arsyad <notifications@github.com>日期： 2020年6月24日周三 下午4:23收件人： xuxingya/tf2crf <tf2crf@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [xuxingya/tf2crf] Unable to save model (#4)
Hi, I'm not able to save the CRF model out after training. Seems that output_dim is not an attribute of the class. Any advise on this?

~/.local/lib/python3.6/site-packages/tf2crf/crf.py in get_config(self)
35     def get_config(self):
36         config = {
---> 37             "output_dim": self.output_dim,
38             "transitions": K.eval(self.transitions),
39         }
AttributeError: 'CRF' object has no attribute 'output_dim'

**Comment by Arsyad-ah** [comment]
hi, i'm now not able to load the model after saving. Getting this error:

`/opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py in validate_kwargs(kwargs, allowed_kwargs, error_message)
    790   for kwarg in kwargs:
    791     if kwarg not in allowed_kwargs:
--> 792       raise TypeError(error_message, kwarg)
    793 
    794 

TypeError: ('Keyword argument not understood:', 'output_dim')`
