### ISSUE TITLE
Unable to load model

### ISSUE THREAD

**Issue by Arsyad-ah** [xuxingya/tf2crf#5]
hi, i'm now not able to load the model after saving. Getting this error:

`/opt/conda/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py in validate_kwargs(kwargs, allowed_kwargs, error_message)
    790   for kwarg in kwargs:
    791     if kwarg not in allowed_kwargs:
--> 792       raise TypeError(error_message, kwarg)
    793 
    794 

TypeError: ('Keyword argument not understood:', 'output_dim')`

**Comment by ravi0912** [comment]
@Arsyad-ah Hey, I'm facing problem while loading the model.
https://github.com/xuxingya/tf2crf/issues/7
Can you tell me How I can load tf model with crf?

**Comment by xuxingya** [comment]
I usually use code like this:
tf.keras.models.save_model(
                model,
                export_path,
                overwrite=True,
                include_optimizer=True,
                save_format=None,
                signatures=None,
                options=None
            )
Then you can :
model.load_weights('model_pathvariables/variables')
or:
model = tf.keras.models.load_model('model_path')
I prefer the previous one, sometimes custom layers have some problems with
the latter one.
It is also compatible with tf serving.

**Comment by ravi0912** [comment]
@xuxingya Thanks it worked..
