### ISSUE TITLE
Possible shape issue when using CRF Loss

### ISSUE THREAD

**Issue by frozaken** [xuxingya/tf2crf#8]
I get the following error
`ValueError: weights can not be broadcast to values. values.rank=0. weights.rank=2. values.shape=(). weights.shape=(None, 200).`

When running this simple sample model to reproduce
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
word_input (InputLayer)      [(None, 200)]             0
_________________________________________________________________
embedding (Embedding)        (None, 200, 100)          100000
_________________________________________________________________
time_distributed_4 (TimeDist (None, 200, 7)            707
_________________________________________________________________
forward_crf (CRF)            (None, 200, 7)            49
=================================================================
```

Using categorical crossentropy lets it train with no issue, but using the loss from the forward_crf layer, give the error instantly. Could this be an issue in the CRF loss?

**Comment by frozaken** [comment]
Could this possibly be related? https://github.com/tensorflow/neural-structured-learning/issues/21

**Comment by xuxingya** [comment]
I run the test code and there is no problem. Could you give me an example code?
